### PR TITLE
Update retry backoff scale to be consistent with conjure-java-runtime

### PR DESCRIPTION
**Pull request by jonsyu1**
See https://github.com/palantir/dialogue/blob/3.90.0/dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java#L372-L378

### CODE REVIEW

**Comment by sfackler** [comment]
Ah nice catch.

Looks like the build's failing with a deprecated method call though.

**Review by sfackler — APPROVED** [review]

**Comment by jonsyu1** [comment]
(still waiting on building gnuplot so I can update the simulations plot)

**Comment by sfackler** [comment]
I just install it via homebrew.

**Comment by sfackler** [comment]
Also wondering if the simulation stuff is even worth having anymore. We haven't done significant work on client side node selection in quite a while, either here or in Dialogue.

**Comment by jonsyu1** [comment]
> I just install it via homebrew.

Yup, homebrew took over 30 minutes so I went to lunch while it ran.

> Also wondering if the simulation stuff is even worth having anymore. We haven't done significant work on client side node selection in quite a while, either here or in Dialogue.

It's trivial to bring it back at a later point when we need it again, so I suggest we remove it in a separate PR.

**Review by sfackler — APPROVED** [review]

**Comment by jonsyu1** [comment]
My simulations panicked locally:
```
thread 'main' panicked at 'attempt to add with overflow', /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/iter/traits/accum.rs:149:1
```
I'll dig more into this when I have time. Or I'll rebase this on top of a PR removing simulations.

**Comment by sfackler** [comment]
https://github.com/palantir/conjure-rust-runtime/pull/163

**Comment by jonsyu1** [comment]
Perfect, thank you. I'll go ahead and rebase

**Pull request merged**
